# Generated by Django 4.2 on 2025-08-10 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import workforce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(default=workforce.models.generate_staff_id, help_text='Unique staff identifier', max_length=255, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='business.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Staff',
                'verbose_name_plural': 'Business Staff',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night'), ('FULL_DAY', 'Full Day')], default='MORNING', max_length=15)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='business.business')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='workforce.businessstaff')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='HoursCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISED', 'Needs Revision')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hours', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours_cards', to='workforce.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_cards', to='workforce.businessstaff')),
            ],
            options={
                'verbose_name': 'Hours Card',
                'verbose_name_plural': 'Hours Cards',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['business', 'is_active'], name='workforce_s_busines_e95095_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['staff', 'day_of_week'], name='workforce_s_staff_i_0a36bc_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shift_type', 'is_active'], name='workforce_s_shift_t_2d5158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('staff', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='hourscard',
            index=models.Index(fields=['staff', 'date'], name='workforce_h_staff_i_f88e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='hourscard',
            index=models.Index(fields=['status', 'date'], name='workforce_h_status_8ccc49_idx'),
        ),
        migrations.AddIndex(
            model_name='hourscard',
            index=models.Index(fields=['approved_by', 'approved_at'], name='workforce_h_approve_a3cb3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourscard',
            unique_together={('staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='businessstaff',
            index=models.Index(fields=['business', 'status'], name='workforce_b_busines_87e6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='businessstaff',
            index=models.Index(fields=['staff_id'], name='workforce_b_staff_i_c0ffe7_idx'),
        ),
        migrations.AddIndex(
            model_name='businessstaff',
            index=models.Index(fields=['user'], name='workforce_b_user_id_a4aa05_idx'),
        ),
        migrations.AddIndex(
            model_name='businessstaff',
            index=models.Index(fields=['employment_type', 'status'], name='workforce_b_employm_790f2a_idx'),
        ),
    ]
