# Generated by Django 4.2 on 2025-11-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='workforce.businessstaff')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
