# Generated by Django 4.2 on 2025-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_staffinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
