# Generated by Django 4.2 on 2025-11-20 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0003_businessstaff_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourscard',
            name='clocked_in_by',
            field=models.ForeignKey(blank=True, help_text='User who performed clock in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clocked_in_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourscard',
            name='clocked_out_by',
            field=models.ForeignKey(blank=True, help_text='User who performed clock out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clocked_out_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourscard',
            name='worker_signature',
            field=models.CharField(blank=True, help_text="Worker's digital signature", max_length=255),
        ),
        migrations.AddField(
            model_name='hourscard',
            name='worker_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed by Worker'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
