# Generated by Django 4.2 on 2025-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_hourscard_clocked_in_by_hourscard_clocked_out_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='clock_in_distance_meters',
            field=models.FloatField(blank=True, help_text='Distance from workplace when clocking in', null=True),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='clock_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Worker's latitude when clocking in", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='clock_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Worker's longitude when clocking in", max_digits=9, null=True),
        ),
    ]
