# Generated by Django 4.2 on 2025-11-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_businessstaff_clock_in_distance_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourscard',
            name='clock_in_datetime',
            field=models.DateTimeField(blank=True, help_text='Full clock-in datetime with timezone', null=True),
        ),
        migrations.AddField(
            model_name='hourscard',
            name='clock_out_datetime',
            field=models.DateTimeField(blank=True, help_text='Full clock-out datetime with timezone', null=True),
        ),
        migrations.AlterField(
            model_name='hourscard',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
