# Generated by Django 4.2 on 2025-08-10 12:06

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('inquiry_type', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('SUPPORT', 'Technical Support'), ('BUSINESS', 'Business Partnership'), ('BUG_REPORT', 'Bug Report'), ('FEATURE_REQUEST', 'Feature Request')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.TextField(max_length=2000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('business_id', models.CharField(default=business.models.generate_business_id, help_text='Unique business identifier', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('RETAIL', 'Retail'), ('HEALTHCARE', 'Healthcare'), ('TECHNOLOGY', 'Technology'), ('CONSTRUCTION', 'Construction'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('SERVICES', 'Services'), ('OTHER', 'Other')], max_length=20)),
                ('size', models.CharField(choices=[('SMALL', '1-10 employees'), ('MEDIUM', '11-50 employees'), ('LARGE', '51-200 employees'), ('ENTERPRISE', '200+ employees')], default='SMALL', max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('service_time', models.TextField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_token', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['inquiry_type', 'is_resolved'], name='business_co_inquiry_d5f01a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['created_at'], name='business_co_created_009be6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'is_verified'], name='business_bu_categor_65c349_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city', 'country'], name='business_bu_city_e4fc87_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_id'], name='business_bu_busines_518aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='business_bu_slug_860a10_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['user', 'is_active'], name='business_bu_user_id_94168c_idx'),
        ),
    ]
