# Generated by Django 4.2 on 2025-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='clock_in_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters for clock-in (default 100m)'),
        ),
        migrations.AddField(
            model_name='business',
            name='require_location_for_clock_in',
            field=models.BooleanField(default=True, help_text='Require workers to be at workplace location to clock in'),
        ),
        migrations.AddField(
            model_name='business',
            name='workplace_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Workplace latitude for clock-in geofencing', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='workplace_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Workplace longitude for clock-in geofencing', max_digits=9, null=True),
        ),
    ]
