# Generated by Django 4.2 on 2025-12-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_clock_in_radius_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='street',
            field=models.CharField(blank=True, help_text='Street name and number (e.g., Plot 45 John Babiha Avenue)', max_length=255),
        ),
    ]
